{% set name = "libspiro" %}
{% set version = "20240902" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/fontforge/libspiro/releases/download/{{ version }}/libspiro-dist-{{ version }}.tar.gz
  sha256: c573228542b3bf78a51c5ce7b0a609e8a2763938a088376230c452c4f9714848

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - make
    - pkg-config
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
  run:

test:
  commands:
    - test -f $PREFIX/lib/libspiro.so  # [unix]

about:
  home: https://github.com/fontforge/libspiro
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  summary: Spiro is the creation of Raph Levien. It simplifies the drawing of beautiful curves.

extra:
  recipe-maintainers:
    - izahn
